### ISSUE TITLE
Ошибка "The command '/bin/sh -c apt update -yqq' returned a non-zero code: 100"

### ISSUE THREAD

**Issue by drdic** [DivanX10/Home-Assistant-Add-on-Deepstack#2]
Здравствуйте! При установке в НА аддона DeepStack Client (DeepStack Trainer) выскакивает ошибка "Не удалось установить дополнение. The command '/bin/sh -c apt update -yqq' returned a non-zero code: 100". При этом, сервер DeepStack Server (CPU) установился нормально. Пожалуйста помогите.

**Comment by DivanX10** [comment]
Рекомендую использовать аддон [double-take](https://github.com/jakowenko/double-take). Отличный аддон. Легко настраивается и подключается к DeepStack server

**Comment by DivanX10** [comment]
Исправил. Теперь аддон DeepStack Trainer работает
