### ISSUE TITLE
Изменился интерфейс

### ISSUE THREAD

**Issue by xes66** [DivanX10/Home-Assistant-Add-on-Deepstack#4]
Привет Дмитрий!
У программы изрядно изменился интерфейс. Если ты еще не удалил у себя эту штуку, не мог бы ты добавить актуальные скрины. Так как тема весьма интересная. Но я не смог до конца это повторить.
Спасибо.

**Comment by DivanX10** [comment]
Аддон AgentDVR переписан и работает. Перенес аддон AgentDVR сюда https://github.com/DivanX10/home-assistant-collection-of-addons
